version: '3'
services:
  php-fpm:
    build: ./docker/php
    container_name: php-fpm
    restart: unless-stopped
    expose:
      - 9000
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: import_test_db
      MYSQL_ROOT_PASSWORD: import_test_password1
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
